Fix air horn
This was causing compilation failures on CPO:

evoke.cc: In function ‘bool evoke_item(int)’:
evoke.cc:1371:71: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
 1371 |           fire_los_attack_spell(SPELL_SONIC_WAVE, spellpower, &you, nullptr);
      |                                                                     ^~~~~~~

Not sure why it worked locally, or why the error has only recently
appeared.